title: Welsh Revenue Authority weeknotes
remote_theme: pages-themes/primer@v0.6.0
permalink: /:categories/:year-:month-:day:output_ext
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-feed
relative_links:
  enabled: true
  collections: false
  # include:
  #   - index.md
  #   - property-data-poc/_posts/*.md
  # exclude:
  #   - README.md
feed:
  categories:
    - property-data-poc